### ISSUE TITLE
RefreshIndicator stops working when 

### ISSUE THREAD

**Issue by Sameerkash** [QuirijnGB/lazy-load-scrollview#4]
RfreshIndicator stops working when LazyLoadScrollView is added to the tree. This makes it really inconvenient as Most ListViews fetching data have a RefreshIndicator. It would be nice if RehreshIndicator still works with LazyLoad

**Comment by dodancs** [comment]
Same problem here!

**Comment by sharpsan** [comment]
I'm sure you aware of the issue by now, just wanted to report that I am experiencing this issue as well.

**Comment by QuirijnGB** [comment]
Hey thanks for raising this. A kind contributor made it possible https://github.com/QuirijnGB/lazy-load-scrollview/pull/5
v1.1.0 should be available now :)
