### ISSUE TITLE
onEndOfPage( ) triggers for every scrollview in the widget tree

### ISSUE THREAD

**Issue by Sameerkash** [QuirijnGB/lazy-load-scrollview#7]
this is how my widget tree looks

```
LazyLoadScrollView(
onEndOfPage: ( ) { }
child: SingleChildScrollView(      //vertical scroll view

child : Column( 
. . . . . 
CarouselSlider (                         //horizontalScrollview
. . . . . 
),
),);
```
onEndOfPage gets triggered for horizontal scroll view too which is not ideal for pagination, which is what I'm using it for, I tried using different scorllControllers, but nothing seems to be working,
Is there any way I can make this work, or can this be implemented in the package? 

Thanks.

**Comment by QuirijnGB** [comment]
Heya, thanks for the feedback. 
Happy for you to open a PR with an initial proposal and we can go from there

**Comment by Sameerkash** [comment]
@QuirijnGB, sure! I am a bit busy now, I'll surely try to work on this as I use it for pagination in all my apps. 
I'll get back to you soon
